version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout

      - run:
          name: Install NPM
          command: npm install

      - run:
          name: Test and build
          command: |
            ./node_modules/.bin/grunt build
            git status
            git status | grep "nothing to commit, working tree clean"
